services:
  stream:
    build:
      context: ./stream
      dockerfile: Dockerfile
    volumes:
      - ./volumes/stream:/stream
    env_file:
      - ./env/stream.env
    restart: unless-stopped
    init: true

  archive:
    build:
      context: ./archive
      dockerfile: Dockerfile
    volumes:
      - ./volumes/archive:/archive
      - ./volumes/stream:/stream:ro
    env_file:
      - ./env/archive.env
    restart: "no"
    init: true
    depends_on:
      - stream

  cronjob:
    build:
      context: ./cronjob
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    depends_on:
      - archive
