version: "3.8"

services:
  recorder:
    build:
      context: ./recorder
      dockerfile: Dockerfile
    volumes:
      - ./volumes/recorder:/recorder
    env_file:
      - ./env/recorder.env
    restart: unless-stopped
    init: true
    ports:
      - "6001:6001"

  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    volumes:
      - ./volumes/backup:/backup
    env_file:
      - ./env/backup.env
    restart: unless-stopped
    init: true
    ports:
      - "6002:6002"
    depends_on:
      - recorder
