services:
  stream:
    build:
      context: ./stream
      dockerfile: Dockerfile
    volumes:
      - ./volumes/stream:/stream
    env_file:
      - ./env/stream.env
    restart: unless-stopped
    init: true

  archive:
    build:
      context: ./archive
      dockerfile: Dockerfile
    volumes:
      - ./volumes/archive:/archive
      - ./volumes/stream:/stream:ro
    env_file:
      - ./env/archive.env
    init: true
    restart: unless-stopped
    depends_on:
      - stream

  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    volumes:
      - ./volumes/archive:/archive:ro
      - ./volumes/stream:/stream:ro
    env_file:
      - ./env/fileserver.env
    init: true
    restart: unless-stopped
    depends_on:
      - stream
      - archive
    ports:
      - 6001:6001

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - fileserver
    # Only start Caddy if CADDY_ENABLED is set to "true"
    # run with `CADDY_ENABLED=true docker compose up`
    profiles: ${CADDY_ENABLED:-false}

volumes:
  caddy_data:
  caddy_config:
